name: Build and Release

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  REGISTRY: ${{ secrets.REGISTRY }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
  CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
  NAMESPACE: ${{ secrets.NAMESPACE }}
  IMAGE: ${{ secrets.REGISTRY }}/PROJECT/IMAGE
  NAME: ${{ secrets.NAME }}
  DOCKERFILE: dockerfile
  MANIFEST: kubernetes.yaml
  VERSION: $GITHUB_RUN_NUMBER
  REPLICAS: 4

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Image Build
        run: docker build . --file ${{ env.DOCKERFILE }} --tag ${{ env.IMAGE }}

      - name: Image Tag Version
        run: docker tag ${{ env.IMAGE }} ${{ env.IMAGE }}:${{ env.VERSION }}

      - name: Registry Login
        uses: docker/login-action@v1.8.0
        with:
          registry: https://${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Image Push
        run: docker push --all-tags ${{ env.IMAGE }}
  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Azure Kubernetes Service Context
        uses: Azure/aks-set-context@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}
          resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}

      - name: Azure Kubernetes Service Create Registry Secret
        uses: Azure/k8s-create-secret@v1.1
        with:
          namespace: ${{ env.NAMESPACE }}
          container-registry-url: https://${{ env.REGISTRY }}
          container-registry-username: ${{ env.REGISTRY_USERNAME }}
          container-registry-password: ${{ env.REGISTRY_PASSWORD }}
          secret-name: secret

      - name: Kubernetes Manifests Replaces
        run: |
          sed -i 's/NAMESPACE/${{ env.NAMESPACE }}/g' ./${{ env.MANIFEST }}
          sed -i 's/NAME/${{ env.NAME }}/g' ./${{ env.MANIFEST }}
          sed -i 's/REPLICAS/${{ env.REPLICAS }}/g' ./${{ env.MANIFEST }}
          sed -i 's/IMAGE/${{ env.IMAGE }}/g' ./${{ env.MANIFEST }}

      - name: Azure Kubernetes Service Deployment
        uses: Azure/k8s-deploy@v1.4
        with:
          namespace: ${{ env.NAMESPACE }}
          manifests: |
            ${{ env.MANIFEST }}
          images: |
            ${{ env.IMAGE }}:${{ env.VERSION }}
          imagepullsecrets: |
            secret
