apiVersion: v1
kind: ConfigMap
immutable: true
metadata:
  name: {{ .Values.name }}-config
  namespace: {{ .Values.namespace }}
data:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
  Serilog__WriteTo__1__Args__path: /logs
